name: Publish Release
on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
jobs:
  build-and-check:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.ANDROID_SIGNING_KEY }}
        run: |
          echo $ENCODED_STRING | base64 -d > keystore.jks

      - name: Assemble Project
        run: ./gradlew clean assembleRelease
        env:
          ORG_GRADLE_PROJECT_androidSigningKeyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

      - name: Cleanup Keystore
        if: ${{ always() }}
        run: rm -f keystore.jks

      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        #        if: ${{ github.ref_type == 'tag' && github.repository == 'ghackett/google-reminder-repeater' }}
        with:
          files: app/build/outputs/apk/release/app-release.apk
